### ISSUE TITLE
Version 2.1.1 does not have files

### ISSUE THREAD

**Issue by chaitanya0bhagvan** [jameslnewell/redux-when#5]
Version 2.1.1 that is available in npm does not contain the code. The last version that does contain any code is 1.0.2

**Comment by avivshafir** [comment]
@jameslnewell the two latest versions do not contain the dist folder
can you please publish a fixed version?
Thanks

**Comment by jameslnewell** [comment]
Good catch. Thanks guys, check out `2.1.2`. 

https://github.com/jameslnewell/redux-when/commit/ba64c67476e1f8fab74584a530918dd724227274
